AWSTemplateFormatVersion: '2010-09-09'
Description: Create NAT Gateway with Elastic IP

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !ImportValue PublicSubnet
      Tags:
        - Key: Name
          Value: nat-gateway
